# Generated by Django 2.1.7 on 2019-03-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(default=None, max_length=140, null=True)),
                ('at', models.DateTimeField(auto_now_add=True, null=True)),
                ('userid', models.CharField(default=None, max_length=140, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieid', models.CharField(max_length=140)),
                ('playcount', models.FloatField(null=True)),
                ('title', models.CharField(max_length=600, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('remove', models.NullBooleanField(default=False)),
                ('userid', models.CharField(default=None, max_length=140, null=True)),
                ('filetype', models.CharField(default='unknown', max_length=140, null=True)),
            ],
        ),
    ]
